<?php
$settings_data = [
    'site_name' => 'Nha Khoa T&A',
    'site_description' => 'Chăm sóc sức khỏe cho răng bạn một cách toàn diện. Chúng tôi không chỉ mang đến nụ cười hoàn hảo, mà còn giúp bạn duy trì sức khỏe răng miệng lâu dài.',
    'site_logo' => 'assets/img/logo.png',
    'site_favicon' => 'assets/img/favicon.png',
    'site_phone' => '0944 492 947',
    'site_email' => 'trongtinacong@gmail.com',
    'site_address' => 'Quận Gò Vấp, TP.HCM',
    'site_working_hours' => 'Thứ 2 - Thứ 6: 7:30 - 17:00
Thứ 7: 7:30 - 12:00
Chủ nhật: Nghỉ',
    'site_facebook' => 'https://www.facebook.com/trong.tin.698908/',
    'site_maps' => '<iframe src=\"<iframe src="<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.858237982653!2d106.68427047508925!3d10.822158889329394!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174deb3ef536f31%3A0x8b7bb8b7c956157b!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBDw7RuZyBuZ2hp4buHcCBUUC5IQ00!5e0!3m2!1svi!2s!4v1747071038030!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
    'site_primary_color' => '#0d6efd',
    'site_enable_appointment' => 1,
    'primary_color' => '#005bac',
    'secondary_color' => '#6c757d',
    'accent_color' => '#28a745',
    'font_family' => 'Roboto, sans-serif',
    'header_bg_color' => '#ffffff',
    'footer_bg_color' => '#f8f9fa',
    'banner_subtitle' => 'Dễ dàng - Nhanh chóng - Tiện lợi',
    'banner_image' => 'assets/img/banner.jpg',
    'site_twitter' => 'https://twitter.com/nhakhoat&a',
    'site_instagram' => 'https://instagram.com/nhakhoat&a',
    'site_youtube' => 'https://youtube.com/nhakhoat&a',
    'site_keywords' => 'phòng khám, đặt lịch khám, bác sĩ, chuyên khoa, dịch vụ y tế, T&A, TP.HCM',
    'enable_booking' => 1,
    'enable_registration' => 1,
    'auto_confirm_booking' => 0,
    'about_image' => 'assets/img/anh-gioithieu.jpg',
    'about_content' => '',
    'site_hotline' => '0944 492 947',
    'site_support_phone' => '012 345 6789',
    'site_support_email' => 'trongtinacong@gmail.com',
    'site_advise_email' => 'dev.trongtin@gmail.com',
    'contact_image' => 'assets/img/anh-gioithieu.jpg',
    'service_title' => 'Dịch vụ chăm sóc răng',
    'service_subtitle' => 'Chăm sóc răng toàn diện với đội ngũ bác sĩ chuyên nghiệp',
    'service_banner_image' => '',
    'doctors_title' => 'Đội ngũ bác sĩ',
    'doctors_subtitle' => 'Các bác sĩ chuyên nghiệp và giàu kinh nghiệm của chúng tôi',
    'doctors_banner_image' => '',
    'specialties_title' => 'Chuyên khoa',
    'specialties_subtitle' => 'Các chuyên khoa khám và điều trị tại phòng khám',
    'specialties_banner_image' => '',
    'smtp_host' => 'smtp.gmail.com',
    'smtp_port' => 587,
    'smtp_encryption' => 'tls',
    'smtp_username' => 'trongtinacong@gmail.com',
    'smtp_password' => 'bsmu qgir tnpl zkse',
    'email_from_name' => 'Nha Khoa T&A',
    'email_test' => '',
];
?>